export enum hotelsTypes {
  FETCH_HOTELS_REQUEST = "FETCH_HOTELS_REQUEST",
  FETCH_HOTELS_SUCCESS = "FETCH_HOTELS_SUCCESS",
  FETCH_HOTELS_FAILURE = "FETCH_HOTELS_FAILURE",
  HOTEL_SET_LIKE = "FETCH_HOTELS_FAILURE",
  HOTEL_UNSET_LIKE = "FETCH_HOTELS_FAILURE",
}
